### ISSUE TITLE
Link "Memory" in README to check_memory README

### ISSUE THREAD

**Issue by quaggoth** [ncr-devops-platform/nagios-foundation#111]
In the main `README.md` there's a "List of Checks" section. Memory is the only check without a link to its corresponding detailed `README.md`. Add the link.

**Comment by Keithncr** [comment]
Resolved with PR #114

**Comment by quaggoth** [comment]
Thanks for trying but wrong direction. You don't link to the PR from the issue. You link from the PR to the issue. You should have had "Resolves #111" in a comment in your original PR.
