### ISSUE TITLE
init_cmd does not belong in the nagiosfoundation API

### ISSUE THREAD

**Issue by quaggoth** [ncr-devops-platform/nagios-foundation#129]
The functions in `lib/app/nagiosfoundation/init_cmd.go` have everything to do with command line flags and [Cobra](https://github.com/spf13/cobra). However, the nagiosfoundation API should know nothing about command line flags or any CLI framework and only act on arguments passed to it.

Move this code into `cmd/` somewhere and give it a package name. Remember that all the commands under `cmd/` must call this so it will probably need its own package name. Perhaps move it to a directory named `cmd/initcmd`, rename the files to remove the underscore, and name the package the same as the directory, `initcmd`.

Remember to update the callers in `cmd/` to import and call this new package. Also update [Gödel](https://github.com/palantir/godel) at `godel/config/dist-plugin.yml` where the version is injected at build time.

Make sure the [Golang Package guidelines](https://blog.golang.org/package-names) are used for naming the package.

Validate the proper version is output with the `version` argument (ex. `check_process version`)

Finally, verify that tests and coverage continue to work with `make test` and `make coverage`.

**Comment by stefanvassilev** [comment]
Hi, can I take this?

**Comment by quaggoth** [comment]
Please do. I'll assign it to me so no one else gets it.
