### ISSUE TITLE
Add option to check_service to output the current service state in nagios format

### ISSUE THREAD

**Issue by quaggoth** [ncr-devops-platform/nagios-foundation#142]
Windows only.

This allows data to be fed to something like influxdb to track the state of a service as it changes.

The new option should be `--current-state (-c)` and would be defined to be:
`--current-state (-c)`: Output the Windows service state in nagios output

The generic command would be of the form
`check_service.exe --name <service> --current_state`

An example would be:
`check_service.exe --name audiosrv --current_state`

The output reflects the state with examples being:
- `CheckService OK - audioserv is in a running state | service_state=0 service_name=audiosrv`
- `CheckService OK - audioserv is in a stopped state | service_state=6 service_name=audiosrv`
- `CheckService OK - audioserv is in a paused state | service_state=1 service_name=audiosrv`

**Comment by quaggoth** [comment]
The state numbers given in the example are:
- 0 - Running
- 1 - Paused
- 2 - Start Pending
- 3 - Pause Pending
- 4 - Continue Pending
- 5 - Stop pending
- 6 - Stopped
- 7 - Unknown
- 255 - No such service

**Comment by Kukunga** [comment]
Sorry for not thinking of this piece until now. We'll want the Linux service check to be consumable in a similar way via nagios perf data > influxdb. In the Zabbix world, 0 = service down and 1 = service up, so it's simpler than the windows states.
