### ISSUE TITLE
Allow check-http to digest JSON formatted data

### ISSUE THREAD

**Issue by tjzero** [ncr-devops-platform/nagios-foundation#151]
Would like to see check-http allow for the verification of json attributes during a check to verify not only a 200 response but also a particular value(s) in the response.

Adding options like: check-http -u https://test/status --format=json --path=“$.api.health.status”  --value “OK”

Would also be beneficial to allow for <> operators as well as equals.

**Comment by jkerry** [comment]
going to need to add accept headers to the check as well

**Comment by shaleenageorge** [comment]
Do these operators work with this command ? < >
command: check_http.exe -u http://localhost:8798/SensuStatus/GetLaneStatus -f json -p "OfflineAmount" -e >1000
![image](https://user-images.githubusercontent.com/51759977/59524556-d0754e80-8e99-11e9-847f-b39fd947b982.png)

**Comment by jkerry** [comment]
Wrap the last string in quotes

**Comment by shaleenageorge** [comment]
Jkerry confirmed that < > operators will not work with this. Opened new issue -
https://github.com/ncr-devops-platform/nagios-foundation/issues/155
