### ISSUE TITLE
Use package mgr to query Windows services

### ISSUE THREAD

**Issue by quaggoth** [ncr-devops-platform/nagios-foundation#44]
Go has a service manager package. Initial research shows it might be a viable alternative to using the current wmi package and might help with memory usage problems we see on one of our test machines.

https://godoc.org/golang.org/x/sys/windows/svc/mgr

Develop some test code to determine if using this package works and if so, implement it in the check_service command. Use a command line switch for the user to select the old wmi method or this service manager package method at run time. This will allow for testing the service manager package when deployed and fall back to wmi if needed.

**Comment by jkerry** [comment]
This sounds great. Let's make sure we test on 32 bit and 64 bit architectures as well. I've got a few test machines spun up when you're ready
