### ISSUE TITLE
OS Support:  Debian

### ISSUE THREAD

**Issue by jkerry** [ncr-devops-platform/nagios-foundation#7]
Add os support for debian. This should be mostly functional already. The service manager for service status check might not be sysstemd

**Comment by quaggoth** [comment]
Debian has used `systemd` as of April, 2015 (https://en.wikipedia.org/wiki/Systemd#Adoption).

I've been testing and coding on Ubuntu 180.04.2 (Debian based) and building and testing inside a Debian 9 (stretch) Docker container for almost 3 months now. So far I haven't uncovered any OS dependent problems except for getting available memory which I've resolved by using the (hopefully)  distribution independent technique of reading `/proc/meminfo` directly.

I feel this issue may be safely closed.

**Comment by quaggoth** [comment]
After some discussion, closing this issue. CentOS is/will be a target OS so functionality must also be checked against CentOS.
